name: sample_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say_hello
        run: echo "hello workflow"
      - name: say_bye
        run: ls
        
